name: poseidon
channels:
  - conda-forge
  - gbrey
dependencies:
  - python=3.9
  - eccodes>2.20
  - geos
  - gmsh=4.8.4
  - jigsaw=0.9.12
  - proj<8
  - pip:
    - -r file:../locks/requirements-full.txt
